### ISSUE TITLE
good job!您好, 能请教一下实现在线编译执行代码的思路吗,用的关键技术是什么呀

### ISSUE THREAD

**Issue by yp199618** [cute-angelia/online-compiler-code#1]
good job! 能请教一下实现在线编译执行代码的思路吗,用的关键技术是什么呀?
看到是用python去写的是吧?

**Comment by cute-angelia** [comment]
@yp199618

原理是生成各个语言的可执行文件，让不同语言环境去执行它，并返回结果

**Comment by yp199618** [comment]
好的了解, 感谢您的回复.
